GoogleSSOTrial/Models/ErrorViewModel.cs
using System;

namespace GoogleSSOTrial.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GoogleSSOTrial/Controllers/GoogleAuthController.cs
using Google.Apis.Auth;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace GoogleSSOTrial.Controllers
{
    [RequireHttps]
    public class GoogleAuthController : Controller
    {

        private readonly ILogger<GoogleAuthController> _logger;

        public GoogleAuthController(ILogger<GoogleAuthController> logger)
        {
            this._logger = logger;
        }


        [HttpPost]
        public IActionResult SignInToken([FromBody] PostModel postModel)
        {
            GoogleJsonWebSignature.Payload payload = GoogleJsonWebSignature.ValidateAsync(postModel.SignInToken).GetAwaiter().GetResult();

            return Json(payload);
        }
    }


    public class PostModel
    {
        public string SignInToken { get; set; }
    }

}

GoogleSSOTrial/Controllers/HomeController.cs
using GoogleSSOTrial.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GoogleSSOTrial.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GoogleSSOTrial/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


<div class="g-signin2" data-onsuccess="onSignIn"></div>
<a href="#" onclick="signOut();">Sign out</a>

<pre id="userdata"></pre>


<script src="https://apis.google.com/js/platform.js" async defer></script>
<meta name="google-signin-client_id" content="985592675497-qtgq7fr3lv0hhp9c1qpmhvmkil8pbhog.apps.googleusercontent.com">

<script>
    function onSignIn(googleUser) {
       
        var profile = googleUser.getBasicProfile();
        console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
        console.log('Name: ' + profile.getName());
        console.log('Image URL: ' + profile.getImageUrl());
        console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.

        var id_token = googleUser.getAuthResponse().id_token;
        console.log('Id Token: ' + id_token);



        jQuery.ajax({
            type: "POST",
            url: "@Url.Action("SignInToken", "GoogleAuth")",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: JSON.stringify({ SignInToken: id_token }),
            success: function (returnData) {
             
                $("#userdata").html(JSON.stringify(returnData, undefined, 2));
            },
            failure: function (errMsg) {
                debugger
                console.log(errorMsg)
                $("#userdata").html(errorMsg);
            }
        });
    }
</script>


<script>
    function signOut() {
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signOut().then(function () {
            $("#userdata").html('');
            console.log('User signed out.');
        });
    }
</script>

GoogleSSOTrial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GoogleSSOTrial</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GoogleSSOTrial</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GoogleSSOTrial - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>